import { defineTypographySpec } from "./define-spec";
import type { TypographySpecDefinition } from "./types";

/**
 * Site-wide type scale — derived from homepage Figma, reusable everywhere.
 * Values (size, weight, font) are exact; ids describe role, not page placement.
 */
export const typographySpecDefinitions = {
  "display-1": defineTypographySpec({
    section: "Display",
    label: "Display · 64px Tiempos italic",
    sample: "Together, We Bring Hope Beyond Cancer",
    family: "tiempos-headline",
    weight: 400,
    fontStyle: "italic",
    desktopPx: 64.0,
    mobilePx: 34.0,
    lineHeight: 1.22,
    letterSpacing: "0em",
    color: "#FFFFFF",
  }),
  "display-2": defineTypographySpec({
    section: "Display",
    label: "Display · 62px Manrope semibold",
    sample: "482+",
    family: "manrope",
    weight: 600,
    fontStyle: "normal",
    desktopPx: 62.0,
    mobilePx: 34.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#2E1C12",
  }),
  "heading-1": defineTypographySpec({
    section: "Headings",
    label: "Heading · 46px Tiempos italic",
    sample: "Our Journey of Impact",
    family: "tiempos-text",
    weight: 400,
    fontStyle: "italic",
    desktopPx: 46.0,
    mobilePx: 28.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#382E07",
    textAlign: "center",
  }),
  "heading-2": defineTypographySpec({
    section: "Headings",
    label: "Heading · 48px Tiempos italic",
    sample: "Cancer Awareness & Screening Camps",
    family: "tiempos-text",
    weight: 400,
    fontStyle: "italic",
    desktopPx: 48.0,
    mobilePx: 30.0,
    lineHeight: 1.4,
    letterSpacing: "0.01em",
    color: "#FFFFFF",
  }),
  "heading-3": defineTypographySpec({
    section: "Headings",
    label: "Heading · 46px Manrope medium",
    sample: "Behind Every Smile Is a Story",
    family: "manrope",
    weight: 500,
    fontStyle: "normal",
    desktopPx: 46.0,
    mobilePx: 28.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#382E07",
    textAlign: "center",
  }),
  "heading-4": defineTypographySpec({
    section: "Headings",
    label: "Heading · 35px Tiempos italic",
    sample: "Sustainable Development Goals",
    family: "tiempos-text",
    weight: 400,
    fontStyle: "italic",
    desktopPx: 35.0,
    mobilePx: 24.0,
    lineHeight: 1.5,
    letterSpacing: "0.02em",
    color: "#FFFFFF",
  }),
  "heading-5": defineTypographySpec({
    section: "Headings",
    label: "Heading · 30px Tiempos italic",
    sample: "Become Someone's Hope",
    family: "tiempos-text",
    weight: 400,
    fontStyle: "italic",
    desktopPx: 29.48,
    mobilePx: 21.0,
    lineHeight: 1.2,
    letterSpacing: "0.01em",
    color: "#FFFFFF",
  }),
  "heading-6": defineTypographySpec({
    section: "Headings",
    label: "Heading · 32px Tiempos Fine italic",
    sample: "Donate Now",
    family: "tiempos-fine",
    weight: 500,
    fontStyle: "italic",
    desktopPx: 32.0,
    mobilePx: 22.0,
    lineHeight: 1.2,
    letterSpacing: "0.02em",
    color: "#FFFFFF",
    textTransform: "capitalize",
  }),
  "heading-7": defineTypographySpec({
    section: "Headings",
    label: "Heading · 28px Manrope bold",
    sample: "Art Therapy & Wellness",
    family: "manrope",
    weight: 700,
    fontStyle: "normal",
    desktopPx: 28.0,
    mobilePx: 20.0,
    lineHeight: 1.5,
    letterSpacing: "0.02em",
    color: "#FFFFFF",
  }),
  "heading-8": defineTypographySpec({
    section: "Headings",
    label: "Heading · 24px Manrope bold",
    sample: "Jatin",
    family: "manrope",
    weight: 700,
    fontStyle: "normal",
    desktopPx: 24.0,
    mobilePx: 18.0,
    lineHeight: 1.5,
    letterSpacing: "0.02em",
    color: "#FFFFFF",
  }),
  "heading-9": defineTypographySpec({
    section: "Headings",
    label: "Heading · 26px Manrope medium",
    sample: "Community Events",
    family: "manrope",
    weight: 500,
    fontStyle: "normal",
    desktopPx: 26.0,
    mobilePx: 20.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#707070",
    textAlign: "center",
  }),
  "body-1": defineTypographySpec({
    section: "Body",
    label: "Body · 26px Argesta centered",
    sample: "Every number represents a life touched, a family supported, and a community strengthened.",
    family: "argesta-display",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 26.0,
    mobilePx: 20.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "rgba(38, 38, 38, 0.55)",
    textAlign: "center",
  }),
  "body-2": defineTypographySpec({
    section: "Body",
    label: "Body · 22px Argesta",
    sample: "Explore the programs and community initiatives that are creating meaningful impact across healthcare.",
    family: "argesta-display",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 22.0,
    mobilePx: 18.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#293239",
  }),
  "body-3": defineTypographySpec({
    section: "Body",
    label: "Body · 20px Argesta",
    sample: "Your Contribution Matters",
    family: "argesta-display",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 20.0,
    mobilePx: 16.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#FFFFFF",
  }),
  "body-4": defineTypographySpec({
    section: "Body",
    label: "Body · 20px Tiempos italic",
    sample: "Awareness & Detection Camps",
    family: "tiempos-text",
    weight: 400,
    fontStyle: "italic",
    desktopPx: 20.0,
    mobilePx: 16.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#000000",
    textAlign: "center",
  }),
  "body-5": defineTypographySpec({
    section: "Body",
    label: "Body · 14px Argesta",
    sample: "Every contribution helps provide care, support, and hope to individuals and families in need.",
    family: "argesta-display",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 14.0,
    mobilePx: 13.0,
    lineHeight: 1.3,
    letterSpacing: "0.02em",
    color: "#FFFFFF",
  }),
  "body-6": defineTypographySpec({
    section: "Body",
    label: "Body · 15px Argesta centered",
    sample: "Your contribution helps us provide care, support and hope to those who need it most.",
    family: "argesta-display",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 15.0,
    mobilePx: 13.0,
    lineHeight: 1.5,
    letterSpacing: "0.03em",
    color: "rgba(255, 255, 255, 0.58)",
    textAlign: "center",
  }),
  "body-7": defineTypographySpec({
    section: "Body",
    label: "Body · 16px Manrope",
    sample: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form.",
    family: "manrope",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 16.0,
    mobilePx: 14.0,
    lineHeight: 1.5,
    letterSpacing: "-0.011em",
    color: "#FFFFFF",
  }),
  "body-8": defineTypographySpec({
    section: "Body",
    label: "Body · 16px Manrope regular",
    sample: "The HCG Foundation is approved under sec 80G of the IT Act.",
    family: "manrope",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 16.0,
    mobilePx: 14.0,
    lineHeight: 1.31,
    letterSpacing: "0.04em",
    color: "#FFFFFF",
  }),
  "body-9": defineTypographySpec({
    section: "Body",
    label: "Body · 18px Manrope regular",
    sample: "Patient Stories",
    family: "manrope",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 18.0,
    mobilePx: 16.0,
    lineHeight: 1.5,
    letterSpacing: "0em",
    color: "#FFFFFF",
  }),
  "body-10": defineTypographySpec({
    section: "Body",
    label: "Body · 20px Argesta lead",
    sample: "Every contribution helps provide care, hope, and essential support to individuals and families.",
    family: "argesta-display",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 20.0,
    mobilePx: 16.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "rgba(255, 255, 255, 0.61)",
  }),
  "label-1": defineTypographySpec({
    section: "UI",
    label: "Label · 15px Manrope",
    sample: "Together We Care",
    family: "manrope",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 14.88,
    mobilePx: 13.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#FFFFFF",
  }),
  "label-2": defineTypographySpec({
    section: "UI",
    label: "Label · 15px Manrope tag",
    sample: "Patient Support",
    family: "manrope",
    weight: 500,
    fontStyle: "normal",
    desktopPx: 14.67,
    mobilePx: 13.0,
    lineHeight: 1.36,
    letterSpacing: "0.05em",
    color: "#FFFFFF",
  }),
  "label-3": defineTypographySpec({
    section: "UI",
    label: "Label · 18px Manrope uppercase",
    sample: "QUICK LINKS",
    family: "manrope",
    weight: 600,
    fontStyle: "normal",
    desktopPx: 18.0,
    mobilePx: 16.0,
    lineHeight: 1.17,
    letterSpacing: "0.04em",
    color: "#FFFFFF",
    textTransform: "uppercase",
  }),
  "text-1": defineTypographySpec({
    section: "UI",
    label: "Text · 18px Manrope bold",
    sample: "Home",
    family: "manrope",
    weight: 700,
    fontStyle: "normal",
    desktopPx: 18.0,
    mobilePx: 16.0,
    lineHeight: 1.39,
    letterSpacing: "0.02em",
    color: "#FFFFFF",
  }),
  "text-2": defineTypographySpec({
    section: "UI",
    label: "Text · 18px Manrope medium",
    sample: "About Us",
    family: "manrope",
    weight: 500,
    fontStyle: "normal",
    desktopPx: 18.0,
    mobilePx: 16.0,
    lineHeight: 1.39,
    letterSpacing: "0.02em",
    color: "#FFFFFF",
  }),
  "button-1": defineTypographySpec({
    section: "UI",
    label: "Button · 18px Manrope semibold",
    sample: "Know More",
    family: "manrope",
    weight: 600,
    fontStyle: "normal",
    desktopPx: 18.0,
    mobilePx: 16.0,
    lineHeight: 1.39,
    letterSpacing: "0em",
    color: "#262626",
  }),
  "button-2": defineTypographySpec({
    section: "UI",
    label: "Button · 12px Manrope medium",
    sample: "Donate Now",
    family: "manrope",
    weight: 500,
    fontStyle: "normal",
    desktopPx: 12.14,
    mobilePx: 11.5,
    lineHeight: 1.3,
    letterSpacing: "0.02em",
    color: "#000000",
  }),
  "button-3": defineTypographySpec({
    section: "UI",
    label: "Button · 16px Manrope semibold",
    sample: "MORE DETAILS",
    family: "manrope",
    weight: 600,
    fontStyle: "normal",
    desktopPx: 16.0,
    mobilePx: 14.0,
    lineHeight: 1.5,
    letterSpacing: "0.02em",
    color: "#212121",
  }),
  "button-4": defineTypographySpec({
    section: "UI",
    label: "Button · 19px Manrope medium",
    sample: "Contact Us",
    family: "manrope",
    weight: 500,
    fontStyle: "normal",
    desktopPx: 18.69,
    mobilePx: 16.0,
    lineHeight: 1.39,
    letterSpacing: "-0.01em",
    color: "#262626",
  }),
  "button-5": defineTypographySpec({
    section: "UI",
    label: "Button · 18px Manrope semibold chip",
    sample: "₹2500",
    family: "manrope",
    weight: 600,
    fontStyle: "normal",
    desktopPx: 17.78,
    mobilePx: 15.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#3C2F02",
  }),
  "button-6": defineTypographySpec({
    section: "UI",
    label: "Button · 18px Manrope semibold submit",
    sample: "Donate Now",
    family: "manrope",
    weight: 600,
    fontStyle: "normal",
    desktopPx: 17.78,
    mobilePx: 15.0,
    lineHeight: 1.5,
    letterSpacing: "0.01em",
    color: "#211007",
  }),
  "caption-1": defineTypographySpec({
    section: "UI",
    label: "Caption · 12px Manrope",
    sample: "2026",
    family: "manrope",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 12.1,
    mobilePx: 11.5,
    lineHeight: 1.3,
    letterSpacing: "0.02em",
    color: "#FFFFFF",
  }),
  "caption-2": defineTypographySpec({
    section: "UI",
    label: "Caption · 16px Manrope",
    sample: "© 2026 The HCG Foundation",
    family: "manrope",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 16.0,
    mobilePx: 14.0,
    lineHeight: 1.75,
    letterSpacing: "0em",
    color: "#000000",
  }),
  "brand-1": defineTypographySpec({
    section: "Brand",
    label: "Brand · Poppins semibold",
    sample: "FOUNDATION",
    family: "poppins",
    weight: 600,
    fontStyle: "normal",
    desktopPx: 16.83,
    mobilePx: 10.0,
    lineHeight: 1.49,
    letterSpacing: "0.03em",
    color: "#FFFFFF",
    textTransform: "uppercase",
  }),
  "brand-2": defineTypographySpec({
    section: "Brand",
    label: "Brand · Roboto regular",
    sample: "Lasting Inspirations",
    family: "roboto",
    weight: 400,
    fontStyle: "normal",
    desktopPx: 12.33,
    mobilePx: 8.0,
    lineHeight: 1.14,
    letterSpacing: "0.03em",
    color: "#FFFFFF",
  }),
} satisfies Record<string, TypographySpecDefinition>;

export type TypographyVariant = keyof typeof typographySpecDefinitions;
